
exports.up = function(knex, Promise) {
  return knex.schema
  .createTable('perfil', table => {
    table.integer('codigo').primary();
    table.string('nome', 255).notNullable();
    table.boolean('admin', false).notNullable();
    table.boolean('ativo', true).notNullable();
  })
  .raw('ALTER TABLE perfil ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY');
};

exports.down = function(knex, Promise) {
  return knex.schema
  .dropTable('perfil');
};
